'''
generate_pcmt.py

This program generates pcmt files using pcc_select.py with the bandpol
selections generated by select_bandpols.py and saved in the file 
'selections_st_<station(s)>_m<median-threshold>.txt'.
 
'''

import numpy as np
import re, os, sys


pcmt = np.loadtxt('pcmt.txt', dtype='a128', delimiter='\n')


sfname = sys.argv[1]   # File name with the bandpol selections

sel_lines = np.loadtxt(sfname, dtype='a256', delimiter='\n')

for sl in sel_lines:
    sels = re.findall('[EGHIVY]:(?:[A-D][XY],*){,8}', sl)
    print(sels)
    print
    
# sels: a list like 
# ['E:AX,AY,BX,BY,CX,CY,DX,DY',
#  'G:BX,BY,CX,CY,DX,DY',
#  'H:AX,AY,BX,BY,CX,CY,DX,DY',
#  'I:CX,CY,DX,DY',
#  'V:AX,AY,BX,BY,CX,CY,DX',
#  'Y:AX,AY,CX,CY']




